#!/usr/bin/env bash
# Mark the EtherCAT USB NIC as unmanaged by NetworkManager and keep PROMISC off.
#
# Why: NetworkManager "Wired connection *" on the r8152 adapter will DHCP, enable
# PROMISC, and flap the link — which kills the SOEM master mid production cycle
# (observed: return_to_backoff_home_a → ethercat drop → backend ERROR).
#
# Usage:
#   sudo bash scripts/network/us-machine-ethercat-unmanaged.sh [iface]
#   sudo bash scripts/network/us-machine-ethercat-unmanaged.sh   # auto-detect
#
# Idempotent. Safe to run at boot / before ethercat_bridge start.
set -euo pipefail

CONF_D="/etc/NetworkManager/conf.d"
CONF_FILE="${CONF_D}/99-us-machine-ethercat-unmanaged.conf"
MAC_FILE="/etc/NetworkManager/conf.d/99-us-machine-ethercat-unmanaged.mac"

log() { echo "us-machine-ethercat-unmanaged: $*"; }

detect_ethercat_nic() {
  local best="" name driver carrier hasip
  for path in /sys/class/net/*; do
    name=$(basename "$path")
    case "$name" in lo|wlan*|tailscale*|docker*|veth*|br-*|end0) continue;; esac
    driver=$(basename "$(readlink -f "$path/device/driver" 2>/dev/null)" 2>/dev/null || true)
    carrier=$(cat "$path/carrier" 2>/dev/null || echo 0)
    hasip=$(ip -o -4 addr show dev "$name" 2>/dev/null || true)
    if [ "$driver" = "r8152" ] && [ "$carrier" = "1" ] && [ -z "$hasip" ]; then
      echo "$name"; return 0
    fi
    if [ "$driver" = "r8152" ] && [ -z "$hasip" ] && [ -z "$best" ]; then
      best="$name"
    fi
  done
  [ -n "$best" ] && { echo "$best"; return 0; }
  return 1
}

IFACE="${1:-}"
if [ -z "$IFACE" ] || [ ! -d "/sys/class/net/$IFACE" ]; then
  IFACE="$(detect_ethercat_nic || true)"
fi
if [ -z "$IFACE" ] || [ ! -d "/sys/class/net/$IFACE" ]; then
  log "ERROR: EtherCAT NIC not found (expected r8152 USB adapter)"
  exit 1
fi

MAC="$(cat "/sys/class/net/$IFACE/address" 2>/dev/null | tr '[:upper:]' '[:lower:]')"
if [ -z "$MAC" ]; then
  log "ERROR: could not read MAC for $IFACE"
  exit 1
fi

log "iface=$IFACE mac=$MAC"

mkdir -p "$CONF_D"

# Persistent: never let NM manage this MAC (survives rename eth1 ↔ enx*).
cat >"$CONF_FILE" <<EOF
# US Machine — EtherCAT fieldbus NIC must stay unmanaged.
# Generated by scripts/network/us-machine-ethercat-unmanaged.sh
[keyfile]
unmanaged-devices=mac:$MAC;interface-name:$IFACE
EOF
echo "$MAC" >"$MAC_FILE"
chmod 644 "$CONF_FILE" "$MAC_FILE"
log "wrote $CONF_FILE"

# Runtime: drop NM management immediately (before reload settles).
if command -v nmcli >/dev/null 2>&1; then
  nmcli device set "$IFACE" managed no 2>/dev/null || true
  # Disable autoconnect on any profile currently bound to this device / MAC.
  while IFS=: read -r name uuid; do
    [ -z "$uuid" ] && continue
    iface_match="$(nmcli -g connection.interface-name connection show "$uuid" 2>/dev/null || true)"
    mac_match="$(nmcli -g 802-3-ethernet.mac-address connection show "$uuid" 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)"
    if [ "$iface_match" = "$IFACE" ] || [ "$mac_match" = "$MAC" ]; then
      log "disabling autoconnect on connection '$name' ($uuid)"
      nmcli connection modify "$uuid" connection.autoconnect no 2>/dev/null || true
      nmcli connection down "$uuid" 2>/dev/null || true
    fi
  done < <(nmcli -t -f NAME,UUID connection show 2>/dev/null || true)

  # Prefer a full reload so keyfile unmanaged-devices takes effect.
  nmcli general reload 2>/dev/null || systemctl reload NetworkManager 2>/dev/null || true
  sleep 0.5
  nmcli device set "$IFACE" managed no 2>/dev/null || true
fi

# Link up, PROMISC off — required for pysoem.
ip link set "$IFACE" up 2>/dev/null || true
ip link set "$IFACE" promisc off 2>/dev/null || true

managed="$(nmcli -g GENERAL.NM-MANAGED device show "$IFACE" 2>/dev/null || echo unknown)"
promisc="$(ip link show "$IFACE" 2>/dev/null | grep -q PROMISC && echo on || echo off)"
state="$(cat "/sys/class/net/$IFACE/operstate" 2>/dev/null || echo unknown)"
log "result managed=$managed promisc=$promisc operstate=$state"
if [ "$managed" = "yes" ]; then
  log "WARN: NM still reports managed=yes — check $CONF_FILE and re-login/reload NM"
  exit 2
fi
exit 0
