#!/bin/bash
# Auto-generated by setup_ethercat_permissions.sh
# Runs Python with cap_net_raw using the real binary + venv site-packages.
export PYTHONPATH="/home/bot/US Machine/venv_ethercat/lib/python3.11/site-packages${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONUNBUFFERED=1
exec "/usr/bin/python3.11" "$@"
