#!/bin/bash
# Grant cap_net_raw and cap_net_admin on the Python binary used by the EtherCAT
# venv. pysoem/SOEM needs both: raw frames (CAP_NET_RAW) and interface setup
# ioctls (CAP_NET_ADMIN). cap_net_raw alone yields EPERM on master.open().
#
# IMPORTANT — symlink chain on Debian/Raspbian:
#   venv/bin/python3  →  /usr/bin/python3  →  /usr/bin/python3.11
#
# Linux drops file capabilities when exec goes through a symlink.
# setcap also refuses to operate on symlinks.
# Solution: set cap_net_raw on EVERY real binary in the chain.
#
# Must be run with sudo: sudo bash scripts/setup_ethercat_permissions.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="$PROJECT_ROOT/venv_ethercat"

echo "=== EtherCAT permissions setup ==="

if [ "$(id -u)" -ne 0 ]; then
    echo "❌ This script must be run as root (sudo)"
    exit 1
fi

if ! command -v setcap &> /dev/null; then
    echo "❌ setcap not found. Install with: sudo apt-get install libcap2-bin"
    exit 1
fi

# ── Collect all real binaries in the symlink chain ────────────────────────────
VENV_PYTHON="$VENV_DIR/bin/python3"

if [ ! -f "$VENV_PYTHON" ]; then
    echo "❌ venv Python not found at $VENV_PYTHON"
    echo "   Run: bash scripts/setup_ethercat_venv.sh"
    exit 1
fi

# Walk the symlink chain and collect every unique real file
declare -A SEEN
TARGETS=()
CURRENT="$VENV_PYTHON"
while true; do
    REAL=$(readlink -f "$CURRENT")
    if [ -z "${SEEN[$REAL]+x}" ]; then
        SEEN[$REAL]=1
        TARGETS+=("$REAL")
    fi
    # If CURRENT itself is a symlink, follow one level to find intermediate targets
    if [ -L "$CURRENT" ]; then
        NEXT=$(readlink "$CURRENT")
        # Make absolute if relative
        if [[ "$NEXT" != /* ]]; then
            NEXT="$(dirname "$CURRENT")/$NEXT"
        fi
        NEXT=$(readlink -f "$NEXT")
        if [ -z "${SEEN[$NEXT]+x}" ]; then
            SEEN[$NEXT]=1
            TARGETS+=("$NEXT")
        fi
        CURRENT="$NEXT"
        [ "$CURRENT" = "$REAL" ] && break
    else
        break
    fi
done

echo "Symlink chain:"
for t in "${TARGETS[@]}"; do
    echo "  $t"
done
echo ""

# ── Apply cap_net_raw,cap_net_admin+ep to every binary in the chain ───────────
for BIN in "${TARGETS[@]}"; do
    if [ -f "$BIN" ]; then
        echo "Setting cap_net_raw,cap_net_admin+ep on $BIN ..."
        setcap 'cap_net_raw,cap_net_admin+ep' "$BIN"
        CAPS=$(getcap "$BIN" 2>/dev/null || echo "")
        if echo "$CAPS" | grep -q "cap_net_raw" && echo "$CAPS" | grep -q "cap_net_admin"; then
            echo "✓ Verified: $CAPS"
        else
            echo "❌ Verification failed for $BIN"
            exit 1
        fi
    fi
done

# ── Write a launcher that uses the real binary + venv PYTHONPATH ──────────────
# This guarantees capabilities are inherited regardless of symlink depth.
LAUNCHER="$SCRIPT_DIR/run_ethercat_python.sh"
SITE_PACKAGES="$VENV_DIR/lib/python3.11/site-packages"
# Auto-detect python version dir
PYVER_DIR=$(ls "$VENV_DIR/lib/" 2>/dev/null | grep -E "^python[0-9]" | head -1)
if [ -n "$PYVER_DIR" ]; then
    SITE_PACKAGES="$VENV_DIR/lib/$PYVER_DIR/site-packages"
fi
REAL_PYTHON="${TARGETS[-1]}"

cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/bash
# Auto-generated by setup_ethercat_permissions.sh
# Runs Python with cap_net_raw using the real binary + venv site-packages.
export PYTHONPATH="$SITE_PACKAGES\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONUNBUFFERED=1
exec "$REAL_PYTHON" "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
echo ""
echo "✓ Launcher written: $LAUNCHER"

echo ""
echo "=== Permissions setup complete ==="
echo ""
echo "Run EtherCAT Python scripts with:"
echo "   bash scripts/run_ethercat_python.sh scripts/ethercat_bridge.py eth1 DigitalIO 'XHS_ECT_050_v2.0 2.xml'"
echo ""
echo "Or for the motor test:"
echo "   bash scripts/run_ethercat_python.sh scripts/test_motor_pp_right.py"
