import { versigentBrand, versigentElevation } from '@/lib/versigentBrand'
import type { ThemePalette } from '@/lib/themeTypes'

const b = versigentBrand

/** Official Versigent brand palette (`Versigent_Color_Palette_Official` in USW.pptx). */
export const versigentPalette: ThemePalette = {
  primary: b.blue,
  primaryDark: b.blueDark,
  primaryDarker: b.blueDarker,
  secondary: b.copper,
  secondaryDark: b.copperDark,
  accent: b.cyan,
  accentGold: b.gold,
  accentBronze: b.bronze,
  brandNavy: b.navy,
  brandCopper: b.copper,
  success: b.green,
  successDark: '#003A1C',
  error: b.error,
  errorDark: b.errorDark,
  errorBg: '#FCEEED',
  warning: b.gold,
  warningDark: b.goldDark,
  info: b.cyan,
  infoBg: '#E8F7FB',
  disabled: b.mutedDark,
  background: b.cream,
  white: b.white,
  grey: '#F3F0EB',
  surfaceElevated: b.white,
  border: b.borderWarm,
  text: b.navy,
  textSecondary: b.muted,
  headerBg: b.navy,
  headerGradient: `linear-gradient(135deg, ${b.navyDeep} 0%, ${b.navy} 48%, ${b.navyLight} 100%)`,
  statusBg: '#E8F1FA',
  statusBorder: b.cyan,
  statusText: b.blueDark,
  statusIdleBg: '#E6F4EA',
  statusIdleBorder: b.greenBright,
  statusIdleText: b.green,
  statusEstopBg: b.errorDark,
  statusEstopBorder: '#7A1F18',
  statusShutdownBg: b.navy,
  statusShutdownBorder: '#2A4054',
  statusShutdownText: b.cream,
  statusShutdownTextMuted: '#A8B4C0',
  statusReinitBg: '#E8F1FA',
  statusReinitBorder: b.blue,
  statusReinitText: b.blueDarker,
  statusStepByStepBg: '#F5F0E8',
  statusStepByStepBorder: b.bronze,
  statusStepByStepText: '#6B4E2A',
  statusSequenceBg: '#E6F4EA',
  statusSequenceBorder: b.green,
  statusSequenceText: b.green,
  shadowCard: versigentElevation.shadowCardLight,
  successBg: '#E6F4EA',
  rowAltBg: '#F7F5F2',
  rowHoverBg: '#E8F1FA',
  rowHighlightBg: '#FFF8E6',
  severityCriticalBg: '#FCEEED',
  severityCriticalText: b.errorDark,
  severityHighBg: '#FDF0E0',
  severityHighText: b.copperDark,
  severityMediumBg: '#FFF8E6',
  severityMediumText: b.goldDark,
  severityLowBg: '#E8F7FB',
  severityLowText: b.blue,
  severityDefaultBg: '#F3F0EB',
  severityDefaultText: b.muted,
  statusActiveBg: '#E6F4EA',
  statusInactiveBg: '#F3F0EB',
  newBadgeColor: b.copper,
  chartSeries: b.chartSeries,
}
